apiVersion: apps/v1
kind: Deployment
metadata:
  name: checking-v1-0-0
  labels:
    app: checking-v1-0-0
    applicationId: app_36f35a6c-64c7-4a5d-9b3b-9bc738c71bee
    version: v1.0.0
    organizationId: org_3ead97cf-c1ec-4b6a-a30e-3a81e9bbbd1a
    projectId: project_429095e6-9936-4562-a9eb-39ee130ec94f
  annotations:
    reloader.stakater.com/auto: 'true'
spec:
  selector:
    matchLabels:
      app: checking-v1-0-0
  template:
    metadata:
      labels:
        app: checking-v1-0-0
        applicationId: app_36f35a6c-64c7-4a5d-9b3b-9bc738c71bee
        version: v1.0.0
        organizationId: org_3ead97cf-c1ec-4b6a-a30e-3a81e9bbbd1a
        projectId: project_429095e6-9936-4562-a9eb-39ee130ec94f
