apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  annotations: {}
  name: new-app-check-v1-0-0
  labels:
    app: new-app-check-v1-0-0
    applicationId: app_4dc31f77-dc34-43ff-8514-685eedaf6263
    version: v1.0.0
    organizationId: org_3ead97cf-c1ec-4b6a-a30e-3a81e9bbbd1a
    projectId: project_939bb6a4-9f53-4587-a860-15820983b92d
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: new-app-check-v1-0-0
