apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  annotations: {}
  name: new-app-v1-0-0
  labels:
    app: new-app-v1-0-0
    applicationId: app_b0d5f6fb-e67c-4e69-9fd9-4021dd3b5e34
    version: v1.0.0
    organizationId: org_3ead97cf-c1ec-4b6a-a30e-3a81e9bbbd1a
    projectId: project_939bb6a4-9f53-4587-a860-15820983b92d
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: new-app-v1-0-0
