apiVersion: transformers.customplugin.co/v1
kind: SkyUAppTransformer
metadata:
  name: skyu-deployment
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: skyu-app-transformer
spec:
  applicationContainers:
    - imageTag: latest
      cpuRequestMili: 100
      cpuLimitMili: 150
      memoryRequestMb: 350
      memoryLimitMb: 450
      args: []
      command: []
      configMounts: []
      applicationPorts:
        - port: 80
          targetPort: 80
          protocol: TCP
      healthChecks: []
      name: new-app-check-main
      imagePullPolicy: Always
      imageRegistry: nginx
  minReplicas: 1
  maxReplicas: 1
  terminationGracePeriodSeconds: 60
  nodeSelector: {}
  suspend: false
  ttlSecondsAfterFinished: 0
  labels:
    app: new-app-check
    version: v1.0.0
    applicationId: app_4dc31f77-dc34-43ff-8514-685eedaf6263
    projectId: project_939bb6a4-9f53-4587-a860-15820983b92d
    organizationId: org_3ead97cf-c1ec-4b6a-a30e-3a81e9bbbd1a
    environmentId: env_a68822fb-9bdd-40f2-8d9f-b42516a09d15
    environmentName: test-env
  horizontalAutoScalingRules: []
  volumes: []
  type: Deployment
  name: new-app-check
  serviceType: ClusterIP
  version: v1.0.0
  namespace: test-ns
